### ISSUE TITLE
how to use atadenoise in ffmpeg

### ISSUE THREAD

**Issue by xsy123xsy** [vi/videomedian#2]
as title mentioned

**Comment by vi** [comment]
```
$ ffmpeg -h filter=atadenoise
Filter atadenoise
  Apply an Adaptive Temporal Averaging Denoiser.
    slice threading supported
    Inputs:
       #0: default (video)
    Outputs:
       #0: default (video)
atadenoise AVOptions:
  0a                <float>      ..FV.....T set threshold A for 1st plane (from 0 to 0.3) (default 0.02)
  0b                <float>      ..FV.....T set threshold B for 1st plane (from 0 to 5) (default 0.04)
  1a                <float>      ..FV.....T set threshold A for 2nd plane (from 0 to 0.3) (default 0.02)
  1b                <float>      ..FV.....T set threshold B for 2nd plane (from 0 to 5) (default 0.04)
  2a                <float>      ..FV.....T set threshold A for 3rd plane (from 0 to 0.3) (default 0.02)
  2b                <float>      ..FV.....T set threshold B for 3rd plane (from 0 to 5) (default 0.04)
  s                 <int>        ..FV...... set how many frames to use (from 5 to 129) (default 9)
  p                 <flags>      ..FV.....T set what planes to filter (default 7)
  a                 <int>        ..FV.....T set variant of algorithm (from 0 to 1) (default p)
     p               0            ..FV.....T parallel
     s               1            ..FV.....T serial
```

There is also example command line in README of this repository.

**Comment by xsy123xsy** [comment]
thx，but I want to use atadenoise with source code by transplanting it to a video engine. Is there any example to call function "ff_atadenoise_init_x86" in "FFmpeg/libavfilter/atadenoise.h"

**Comment by vi** [comment]
I don't expect usage of this filter from C to be significantly different compared to usage of other FFmpeg video filters.

I recommend to use the [API documentation](https://www.ffmpeg.org/doxygen/4.0/) and examples such as [this](https://ffmpeg.org/doxygen/2.1/doc_2examples_2filtering_video_8c-example.html), reaching for the [maillist](https://ffmpeg.org/contact.html) or IRC only if you can't use or don't understand the documentation or examples or if there is something wrong with `atadenoise` filter specifically.

Note: this issue is off-topic in this repository.

**Comment by xsy123xsy** [comment]
I want to learn more about atadenoise in ffmpeg, Can we contact by email?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vitaly Shukela"<notifications@github.com&gt;; 
发送时间: 2021年2月22日(星期一) 晚上8:21
收件人: "vi/videomedian"<videomedian@noreply.github.com&gt;; 
抄送: "xsy_xsy"<366366235@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [vi/videomedian] how to use atadenoise in ffmpeg (#2)





 
I don't expect usage of this filter from C to be significantly different that usage of other FFmpeg video filters.
 
I recommend to use the API documentation and examples such as this, reaching for the maillist or IRC only if you can't use or don't understand the documentation or examples or if there is something wrong with atadenoise filter specifically.
 
Note: this issue is off-topic in this repository.
